id: 6c1a8053-f982-4505-b5d9-89682ddadca2
post_type: video
title: Augmenting the Ethereum Rollup Stack via Shared Security
published_date: 2023-09-03T12:26:42.434Z
video:
  url: https://www.youtube.com/watch?v=BdmShzOXHRQ&list=PLcIyXLwiPilX2ncKfmXRSUPQ21AN-JaRo&index=9
  id: BdmShzOXHRQ
  data:
    kind: youtube#video
    etag: BZYZlubz_iy4n3hsYhls7ZGPhfU
    id: BdmShzOXHRQ
    snippet:
      publishedAt: 2023-09-03T09:37:38.000Z
      liveBroadcastContent: none
      thumbnails:
        default:
          url: https://i.ytimg.com/vi/BdmShzOXHRQ/default.jpg
          width: 120
          height: 90
        medium:
          url: https://i.ytimg.com/vi/BdmShzOXHRQ/mqdefault.jpg
          width: 320
          height: 180
        high:
          url: https://i.ytimg.com/vi/BdmShzOXHRQ/hqdefault.jpg
          width: 480
          height: 360
        standard:
          url: https://i.ytimg.com/vi/BdmShzOXHRQ/sddefault.jpg
          width: 640
          height: 480
        maxres:
          url: https://i.ytimg.com/vi/BdmShzOXHRQ/maxresdefault.jpg
          width: 1280
          height: 720
      defaultAudioLanguage: en-US
      channelTitle: StarkWare
      title: Augmenting the Ethereum Rollup Stack via Shared Security | Sreeram Kannan
      categoryId: "28"
      localized:
        title: Augmenting the Ethereum Rollup Stack via Shared Security | Sreeram Kannan
        description: In this talk, we highlight how restaking and shared security can
          play a vital role in augmenting the rollup stack. We showcase how
          EigenLayer can be used to build a variety of solutions that complement
          the Ethereum rollup stack, including a hyperscale Data Availability
          layer, modular MEV management solutions, bridging solutions across
          rollups, decentralized sequencing, superfast settlement with high
          economic security.
      description: In this talk, we highlight how restaking and shared security can
        play a vital role in augmenting the rollup stack. We showcase how
        EigenLayer can be used to build a variety of solutions that complement
        the Ethereum rollup stack, including a hyperscale Data Availability
        layer, modular MEV management solutions, bridging solutions across
        rollups, decentralized sequencing, superfast settlement with high
        economic security.
      channelId: UCnDWguR8mE2oDBsjhQkgbvg
    contentDetails:
      duration: PT17M39S
      dimension: 2d
      definition: hd
      caption: "false"
      licensedContent: false
      contentRating: {}
      projection: rectangular
image: /assets/youthumb_bdmshzoxhrq_maxres.png
category:
  - community-and-events
  - 67da7f3a-f26c-430c-92e1-95d58ed5b597
  - ecosystem
topic:
  - 266fa988-350c-4842-b74e-379068ddcf34
  - ef41aa70-6d30-4d4d-9543-10ffd53a1587
  - decentralization
short_desc: This talk highlights how re-staking and shared security can play a
  vital role in augmenting the rollup stack. It showcases how EigenLayer can be
  used to build a variety of solutions that complement the Ethereum rollup
  stack, including a hyperscale Data Availability layer, modular MEV management
  solutions, bridging solutions across rollups, decentralized sequencing,
  superfast settlement with high economic security.
