project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /_data/categories/en/*.json
    translation: /_data/categories/%two_letters_code%/%original_file_name%
  - source: /_data/events/en/*.json
    translation: /_data/events/%two_letters_code%/%original_file_name%
  - source: /_data/i18n/en/*.json
    translation: /_data/i18n/%two_letters_code%/%original_file_name%
  - source: /_data/jobs/en/*.json
    translation: /_data/jobs/%two_letters_code%/%original_file_name%
  - source: /_data/pages/en/*.json
    translation: /_data/pages/%two_letters_code%/%original_file_name%
  - source: /_data/posts/en/*.json
    translation: /_data/posts/%two_letters_code%/%original_file_name%
  - source: /_data/settings/en/*.json
    translation: /_data/settings/%two_letters_code%/%original_file_name%
  - source: /_data/topics/en/*.json
    translation: /_data/topics/%two_letters_code%/%original_file_name%
  - source: /_data/tutorials/en/*.json
    translation: /_data/tutorials/%two_letters_code%/%original_file_name%
  - source: /i18n/intl/en.json
    translation: /i18n/intl/%two_letters_code%.json
