id: b7e5af4c-1ecf-4ef2-bf86-51a8850c2afa
title: Starknet’s security
template: content
parent_page: /learn/
breadcrumbs: true
page_last_updated: true
blocks:
  - type: page_header
    title: Starknet's security
  - type: markdown
    body: >-
      Starknet’s security
