export const tokens = {
  colors: {
    light: {
      "bg-default": "#FBFBFB",
      "fg-default": "#6B7280",
      "fg-muted": "#858585",
      "fg-accent": "#E97880",
      "navbar-bg": "#FFFFFF",
      "navbar-dropdown-bg": "#FFFFFF",
      "button-nav-bg": "transparent",
      "button-nav-fg": "#363636",
      "button-nav-icon-fg": "#CCCCCC",
      "button-nav-hover-bg": "#FBFBFB",
      "button-nav-hover-fg": "#363636",
      "button-nav-hover-icon-fg": "#5C94FF",
      "button-nav-active-bg": "#FBFBFB",
      "button-nav-active-fg": "#363636",
      "button-nav-active-icon-fg": "#CCCCCC",
      "button-nav-focus-br": "#5C94FF",
      "btn-outline-bg": "transparent",
      "btn-outline-fg": "#6B7280",
      "btn-outline-border": "#EFEFEF",
      "btn-outline-hover-bg": "transparent",
      "btn-outline-hover-fg": "#5C94FF",
      "btn-outline-hover-border": "#5C94FF",
      "btn-outline-active-bg": "#EFEFEF",
      "btn-outline-active-fg": "#6B7280",
      "btn-outline-active-border": "#EFEFEF",
      "btn-bg": "",
      "btn-hover-bg": "",
      "btn-active-bg": "",
      "btn-fg": "",
      "btn-hover-fg": "",
      "btn-active-fg": "",
      "btn-border": "",
      "btn-hover-border": "",
      "btn-active-border": "",
      "btn-primary-bg": "#0C0C4F",
      "btn-primary-hover-bg": "#0C0C4F",
      "btn-primary-active-bg": "#0C0C4F",
      "btn-primary-fg": "#FFFFFF",
      "btn-primary-hover-fg": "#FFFFFF",
      "btn-primary-active-fg": "#FFFFFF",
      "btn-primary-border": "#0C0C4F",
      "btn-primary-hover-border": "#0C0C4F",
      "btn-primary-active-border": "#0C0C4F",
      "article-card-bg": "#FFFFFF",
      "card-bg": "#FFFFFF",
      "subnav-fg": "#858585",
      "subnav-fg-accent": "#0C0C4F",
      "heading-navy-fg": "#0C0C4F",
      "columnlink-bg": "transparent",
      "columnlink-fg": "#6B7280",
      "columnlink-hover-bg": "#FBFBFB",
      "columnlink-hover-fg": "#5C94FF",
      "columnlink-active-bg": "#FFFFFF",
      "columnlink-active-fg": "#0C0C4F",
      "divider-bg": "#EFEFEF",
      "navbar-link-bg": "transparent",
      "navbar-link-fg": "#6B7280",
      "navbar-link-hover-bg": "#FBFBFB",
      "navbar-link-hover-fg": "#5C94FF",
      "navbar-link-active-bg": "transparent",
      "navbar-link-active-fg": "#2166EF",
      "navbar-link-visited-bg": "transparent",
      "navbar-link-visited-fg": "#2166EF",
      "nav-dialog-bg": "#FBFBFB",
      "nav-header-bg": "#ffffff",
      "nav-accordian-expanded-bg": "#0C0C4F",
      "nav-accordian-expanded-fg": "#FFFFFF",
      "nav-footer-br": "#EFEFEF",
      "nav-searchinput-bg": "#F6F6F6",
      "nav-searchinput-fg": "#858585",
      "nav-searchinput-br": "#F6F6F6",
      "nav-searchinput-hover-br": "#EFEFEF",
      "nav-searchinput-hover-bg": "#F6F6F6",
      "nav-searchinput-hover-fg": "#5C94FF",
      "kbd-bg": "#cccccc",
      "kbd-fg": "#363636",
    },

    dark: {
      "bg-default": "#0B0B0B",
      "fg-default": "#CCCCCC",
      "fg-muted": "#7E7E7E",
      "fg-accent": "#FE9E92",
      "navbar-bg": "#121212",
      "navbar-dropdown-bg": "#1B1B1B",
      "button-nav-bg": "transparent",
      "button-nav-fg": "#FFFFFF",
      "button-nav-icon-fg": "#7E7E7E",
      "button-nav-hover-bg": "#000000",
      "button-nav-hover-fg": "#FFFFFF",
      "button-nav-hover-icon-fg": "#AFCAFF",
      "button-nav-active-bg": "#000000",
      "button-nav-active-fg": "#7E7E7E",
      "button-nav-active-icon-fg": "#7E7E7E",
      "button-nav-focus-br": "#AFCAFF",
      "btn-outline-bg": "transparent",
      "btn-outline-fg": "#ffffff",
      "btn-outline-border": "#7E7E7E",
      "btn-outline-hover-bg": "transparent",
      "btn-outline-hover-fg": "#9EBFFF",
      "btn-outline-hover-border": "#9EBFFF",
      "btn-outline-active-bg": "#000000",
      "btn-outline-active-fg": "#858585",
      "btn-outline-active-border": "#000000",
      "btn-bg": "",
      "btn-hover-bg": "",
      "btn-active-bg": "",
      "btn-fg": "",
      "btn-hover-fg": "",
      "btn-active-fg": "",
      "btn-border": "",
      "btn-hover-border": "",
      "btn-active-border": "",
      "btn-primary-bg": "#5C94FF",
      "btn-primary-hover-bg": "#5C94FF",
      "btn-primary-active-bg": "#5C94FF",
      "btn-primary-fg": "#FFFFFF",
      "btn-primary-hover-fg": "#FFFFFF",
      "btn-primary-active-fg": "#FFFFFF",
      "btn-primary-border": "#5C94FF",
      "btn-primary-hover-border": "#5C94FF",
      "btn-primary-active-border": "#5C94FF",
      "article-card-bg": "#1B1B1B",
      "card-bg": "#1B1B1B",
      "subnav-fg": "#7E7E7E",
      "subnav-fg-accent": "#ffffff",
      "heading-navy-fg": "#FFFFFF",
      "columnlink-bg": "transparent",
      "columnlink-fg": "#CCCCCC",
      "columnlink-hover-bg": "#121212",
      "columnlink-hover-fg": "#9EBFFF",
      "columnlink-active-bg": "transparent",
      "columnlink-active-fg": "#9EBFFF",
      "divider-bg": "#313131",
      "navbar-link-bg": "transparent",
      "navbar-link-fg": "#CCCCCC",
      "navbar-link-hover-bg": "#121212",
      "navbar-link-hover-fg": "#9EBFFF",
      "navbar-link-active-bg": "transparent",
      "navbar-link-active-fg": "#2166EF",
      "navbar-link-visited-bg": "transparent",
      "navbar-link-visited-fg": "#2166EF",
      "nav-dialog-bg": "#1B1B1B",
      "nav-header-bg": "#000000",
      "nav-accordian-expanded-bg": "#AFCAFF",
      "nav-accordian-expanded-fg": "#121212",
      "nav-footer-br": "#313131",
      "nav-searchinput-bg": "#1B1B1B",
      "nav-searchinput-fg": "#AFCAFF",
      "nav-searchinput-br": "#1B1B1B",
      "nav-searchinput-hover-br": "#858585",
      "nav-searchinput-hover-bg": "#000000",
      "nav-searchinput-hover-fg": "#AFCAFF",
      "kbd-bg": "#313131",
      "kbd-fg": "#CCCCCC",
    },
  },
};

export const semanticTokens = {
  colors: {
    "bg-default": {
      default: tokens.colors.light["bg-default"],
      _dark: tokens.colors.dark["bg-default"],
    },
    "fg-default": {
      default: tokens.colors.light["fg-default"],
      _dark: tokens.colors.dark["fg-default"],
    },
    "fg-muted": {
      default: tokens.colors.light["fg-muted"],
      _dark: tokens.colors.dark["fg-muted"],
    },
    "fg-accent": {
      default: tokens.colors.light["fg-accent"],
      _dark: tokens.colors.dark["fg-accent"],
    },
    "navbar-bg": {
      default: tokens.colors.light["navbar-bg"],
      _dark: tokens.colors.dark["navbar-bg"],
    },
    "navbar-dropdown-bg": {
      default: tokens.colors.light["navbar-dropdown-bg"],
      _dark: tokens.colors.dark["navbar-dropdown-bg"],
    },
    // "navlink-fg": {
    //   default: tokens.colors.light["navlink-fg"],
    //   _dark: tokens.colors.dark["navlink-fg"],
    // },
    "btn-bg": {
      default: tokens.colors.light["btn-bg"],
      _dark: tokens.colors.dark["btn-bg"],
    },
    "btn-hover-bg": {
      default: tokens.colors.light["btn-hover-bg"],
      _dark: tokens.colors.dark["btn-hover-bg"],
    },
    "btn-active-bg": {
      default: tokens.colors.light["btn-active-bg"],
      _dark: tokens.colors.dark["btn-active-bg"],
    },
    "btn-fg": {
      default: tokens.colors.light["btn-fg"],
      _dark: tokens.colors.dark["btn-fg"],
    },
    "btn-hover-fg": {
      default: tokens.colors.light["btn-hover-fg"],
      _dark: tokens.colors.dark["btn-hover-fg"],
    },
    "btn-active-fg": {
      default: tokens.colors.light["btn-active-fg"],
      _dark: tokens.colors.dark["btn-active-fg"],
    },
    "btn-border": {
      default: tokens.colors.light["btn-border"],
      _dark: tokens.colors.dark["btn-border"],
    },
    "btn-hover-border": {
      default: tokens.colors.light["btn-hover-border"],
      _dark: tokens.colors.dark["btn-hover-border"],
    },
    "btn-active-border": {
      default: tokens.colors.light["btn-active-border"],
      _dark: tokens.colors.dark["btn-active-border"],
    },

    "btn-primary-bg": {
      default: tokens.colors.light["btn-primary-bg"],
      _dark: tokens.colors.dark["btn-primary-bg"],
    },
    "btn-primary-hover-bg": {
      default: tokens.colors.light["btn-primary-hover-bg"],
      _dark: tokens.colors.dark["btn-primary-hover-bg"],
    },
    "btn-primary-active-bg": {
      default: tokens.colors.light["btn-primary-active-bg"],
      _dark: tokens.colors.dark["btn-primary-active-bg"],
    },
    "btn-primary-fg": {
      default: tokens.colors.light["btn-primary-fg"],
      _dark: tokens.colors.dark["btn-primary-fg"],
    },
    "btn-primary-hover-fg": {
      default: tokens.colors.light["btn-primary-hover-fg"],
      _dark: tokens.colors.dark["btn-primary-hover-fg"],
    },
    "btn-primary-active-fg": {
      default: tokens.colors.light["btn-primary-active-fg"],
      _dark: tokens.colors.dark["btn-primary-active-fg"],
    },
    "btn-primary-border": {
      default: tokens.colors.light["btn-primary-border"],
      _dark: tokens.colors.dark["btn-primary-border"],
    },
    "btn-primary-hover-border": {
      default: tokens.colors.light["btn-primary-hover-border"],
      _dark: tokens.colors.dark["btn-primary-hover-border"],
    },
    "btn-primary-active-border": {
      default: tokens.colors.light["btn-primary-active-border"],
      _dark: tokens.colors.dark["btn-primary-active-border"],
    },
    "article-card-bg": {
      default: tokens.colors.light["article-card-bg"],
      _dark: tokens.colors.dark["article-card-bg"],
    },
    "card-bg": {
      default: tokens.colors.light["card-bg"],
      _dark: tokens.colors.dark["card-bg"],
    },
    "subnav-fg": {
      default: tokens.colors.light["subnav-fg"],
      _dark: tokens.colors.dark["subnav-fg"],
    },
    "subnav-fg-accent": {
      default: tokens.colors.light["subnav-fg-accent"],
      _dark: tokens.colors.dark["subnav-fg-accent"],
    },
    "heading-navy-fg": {
      default: tokens.colors.light["heading-navy-fg"],
      _dark: tokens.colors.dark["heading-navy-fg"],
    },
    "columnlink-bg": {
      default: tokens.colors.light["columnlink-bg"],
      _dark: tokens.colors.dark["columnlink-bg"],
    },
    "columnlink-fg": {
      default: tokens.colors.light["columnlink-fg"],
      _dark: tokens.colors.dark["columnlink-fg"],
    },
    "columnlink-hover-bg": {
      default: tokens.colors.light["columnlink-hover-bg"],
      _dark: tokens.colors.dark["columnlink-hover-bg"],
    },
    "columnlink-hover-fg": {
      default: tokens.colors.light["columnlink-hover-fg"],
      _dark: tokens.colors.dark["columnlink-hover-fg"],
    },
    "columnlink-active-bg": {
      default: tokens.colors.light["columnlink-active-bg"],
      _dark: tokens.colors.dark["columnlink-active-bg"],
    },
    "columnlink-active-fg": {
      default: tokens.colors.light["columnlink-active-fg"],
      _dark: tokens.colors.dark["columnlink-active-fg"],
    },
    "btn-outline-bg": {
      default: tokens.colors.light["btn-outline-bg"],
      _dark: tokens.colors.dark["btn-outline-bg"],
    },
    "btn-outline-fg": {
      default: tokens.colors.light["btn-outline-fg"],
      _dark: tokens.colors.dark["btn-outline-fg"],
    },
    "btn-outline-border": {
      default: tokens.colors.light["btn-outline-border"],
      _dark: tokens.colors.dark["btn-outline-border"],
    },
    "btn-outline-hover-border": {
      default: tokens.colors.light["btn-outline-hover-border"],
      _dark: tokens.colors.dark["btn-outline-hover-border"],
    },
    "btn-outline-hover-fg": {
      default: tokens.colors.light["btn-outline-hover-fg"],
      _dark: tokens.colors.dark["btn-outline-hover-fg"],
    },
    "btn-outline-active-bg": {
      default: tokens.colors.light["btn-outline-active-bg"],
      _dark: tokens.colors.dark["btn-outline-active-bg"],
    },
    "btn-outline-active-fg": {
      default: tokens.colors.light["btn-outline-active-fg"],
      _dark: tokens.colors.dark["btn-outline-active-fg"],
    },
    "btn-outline-active-border": {
      default: tokens.colors.light["btn-outline-active-border"],
      _dark: tokens.colors.dark["btn-outline-active-border"],
    },
    "navbar-link-bg": {
      default: tokens.colors.light["navbar-link-bg"],
      _dark: tokens.colors.dark["navbar-link-bg"],
    },
    "navbar-link-fg": {
      default: tokens.colors.light["navbar-link-fg"],
      _dark: tokens.colors.dark["navbar-link-fg"],
    },
    "navbar-link-hover-bg": {
      default: tokens.colors.light["navbar-link-hover-bg"],
      _dark: tokens.colors.dark["navbar-link-hover-bg"],
    },
    "navbar-link-active-bg": {
      default: tokens.colors.light["navbar-link-active-bg"],
      _dark: tokens.colors.dark["navbar-link-active-bg"],
    },
    "navbar-link-hover-fg": {
      default: tokens.colors.light["navbar-link-hover-fg"],
      _dark: tokens.colors.dark["navbar-link-hover-fg"],
    },
    "navbar-link-active-fg": {
      default: tokens.colors.light["navbar-link-active-fg"],
      _dark: tokens.colors.dark["navbar-link-active-fg"],
    },
    "navbar-link-visited-bg": {
      default: tokens.colors.light["navbar-link-visited-bg"],
      _dark: tokens.colors.dark["navbar-link-visited-bg"],
    },
    "navbar-link-visited-fg": {
      default: tokens.colors.light["navbar-link-visited-fg"],
      _dark: tokens.colors.dark["navbar-link-visited-fg"],
    },
    "nav-dialog-bg": {
      default: tokens.colors.light["nav-dialog-bg"],
      _dark: tokens.colors.dark["nav-dialog-bg"],
    },
    "nav-header-bg": {
      default: tokens.colors.light["nav-header-bg"],
      _dark: tokens.colors.dark["nav-header-bg"],
    },
    "nav-accordian-expanded-bg": {
      default: tokens.colors.light["nav-accordian-expanded-bg"],
      _dark: tokens.colors.dark["nav-accordian-expanded-bg"],
    },
    "nav-accordian-expanded-fg": {
      default: tokens.colors.light["nav-accordian-expanded-fg"],
      _dark: tokens.colors.dark["nav-accordian-expanded-fg"],
    },
    "nav-footer-br": {
      default: tokens.colors.light["nav-footer-br"],
      _dark: tokens.colors.dark["nav-footer-br"],
    },
    "nav-searchinput-bg": {
      default: tokens.colors.light["nav-searchinput-bg"],
      _dark: tokens.colors.dark["nav-searchinput-bg"],
    },
    "nav-searchinput-fg": {
      default: tokens.colors.light["nav-searchinput-fg"],
      _dark: tokens.colors.dark["nav-searchinput-fg"],
    },
    "nav-searchinput-hover-bg": {
      default: tokens.colors.light["nav-searchinput-hover-bg"],
      _dark: tokens.colors.dark["nav-searchinput-hover-bg"],
    },
    "nav-searchinput-hover-fg": {
      default: tokens.colors.light["nav-searchinput-hover-fg"],
      _dark: tokens.colors.dark["nav-searchinput-hover-fg"],
    },
    "nav-searchinput-br": {
      default: tokens.colors.light["nav-searchinput-br"],
      _dark: tokens.colors.dark["nav-searchinput-br"],
    },
    "nav-searchinput-hover-br": {
      default: tokens.colors.light["nav-searchinput-hover-br"],
      _dark: tokens.colors.dark["nav-searchinput-hover-br"],
    },
    "kbd-bg": {
      default: tokens.colors.light["kbd-bg"],
      _dark: tokens.colors.dark["kbd-bg"],
    },
    "kbd-fg": {
      default: tokens.colors.light["kbd-fg"],
      _dark: tokens.colors.dark["kbd-fg"],
    },

    "button-nav-bg": {
      default: tokens.colors.light["button-nav-bg"],
      _dark: tokens.colors.dark["button-nav-bg"],
    },
    "button-nav-fg": {
      default: tokens.colors.light["button-nav-fg"],
      _dark: tokens.colors.dark["button-nav-fg"],
    },
    "button-nav-icon-fg": {
      default: tokens.colors.light["button-nav-icon-fg"],
      _dark: tokens.colors.dark["button-nav-icon-fg"],
    },
    "button-nav-hover-bg": {
      default: tokens.colors.light["button-nav-hover-bg"],
      _dark: tokens.colors.dark["button-nav-hover-bg"],
    },
    "button-nav-hover-fg": {
      default: tokens.colors.light["button-nav-hover-fg"],
      _dark: tokens.colors.dark["button-nav-hover-fg"],
    },
    "button-nav-hover-icon-fg": {
      default: tokens.colors.light["button-nav-hover-icon-fg"],
      _dark: tokens.colors.dark["button-nav-hover-icon-fg"],
    },
    "button-nav-active-bg": {
      default: tokens.colors.light["button-nav-active-bg"],
      _dark: tokens.colors.dark["button-nav-active-bg"],
    },
    "button-nav-active-fg": {
      default: tokens.colors.light["button-nav-active-fg"],
      _dark: tokens.colors.dark["button-nav-active-fg"],
    },
    "button-nav-active-icon-fg": {
      default: tokens.colors.light["button-nav-active-icon-fg"],
      _dark: tokens.colors.dark["button-nav-active-icon-fg"],
    },
    "button-nav-focus-br": {
      default: tokens.colors.light["button-nav-focus-br"],
      _dark: tokens.colors.dark["button-nav-focus-br"],
    },
    "divider-bg": {
      default: tokens.colors.light["divider-bg"],
      _dark: tokens.colors.dark["divider-bg"],
    },
  },
};
