export const tokens = {
  colors: {
    light: {
      "listLink-fg": "#5C94FF",
      "bg-default": "#FBFBFB",
      "fg-default": "#6B7280",
      "fg-muted": "#858585",
      "fg-accent": "#E97880",
      "navbar-bg": "#FFFFFF",
      "navbar-dropdown-bg": "#FFFFFF",
      "button-nav-bg": "transparent",
      "button-nav-fg": "#363636",
      "button-nav-icon-fg": "#CCCCCC",
      "button-nav-hover-bg": "#FBFBFB",
      "button-nav-hover-fg": "#363636",
      "button-nav-hover-icon-fg": "#5C94FF",
      "button-nav-active-bg": "#FBFBFB",
      "button-nav-active-fg": "#363636",
      "button-nav-active-icon-fg": "#CCCCCC",
      "button-nav-focus-br": "#5C94FF",
      "btn-outline-bg": "transparent",
      "btn-outline-fg": "#6B7280",
      "btn-outline-border": "#EFEFEF",
      "btn-outline-hover-bg": "transparent",
      "btn-outline-hover-fg": "#5C94FF",
      "btn-outline-hover-border": "#5C94FF",
      "btn-outline-active-bg": "#EFEFEF",
      "btn-outline-active-fg": "#6B7280",
      "btn-outline-active-border": "#EFEFEF",
      "btn-bg": "",
      "btn-hover-bg": "",
      "btn-active-bg": "",
      "btn-fg": "",
      "btn-hover-fg": "",
      "btn-active-fg": "",
      "btn-border": "",
      "btn-hover-border": "",
      "btn-active-border": "",
      "btn-primary-bg": "#0C0C4F",
      "btn-primary-hover-bg": "#131365",
      "btn-primary-active-bg": "#150E1F",
      "btn-primary-fg": "#FFFFFF",
      "btn-primary-hover-fg": "#FFFFFF",
      "btn-primary-active-fg": "#6B7280",
      "btn-primary-border": "#0C0C4F",
      "btn-primary-hover-border": "#0C0C4F",
      "btn-primary-active-border": "#0C0C4F",
      "article-card-bg": "#FFFFFF",
      "card-bg": "#FFFFFF",
      "roadmap-hero-card-bg": "#F8F8F8",
      "roadmap-hero-gradient": "linear-gradient(280.23deg, #EAF7FF 0%, #FAFDFF 100%, #EEFAFF 100%), linear-gradient(280.23deg, #EAF7FF 0%, #FAFDFF 100%, #EEFAFF 100%), linear-gradient(280.23deg, #DEF7FD 0%, #F4FDFF 100%), #F8F8F8",
      "roadmap-hero-arrow-gradient": "linear(45deg, #82BDBD 100%, #4F6D87 100%)",
      "card-br": "#EFEFEF",
      "subnav-fg": "#858585",
      "subnav-fg-accent": "#0C0C4F",
      "heading-navy-fg": "#0C0C4F",
      "columnlink-bg": "transparent",
      "columnlink-fg": "#6B7280",
      "tutorials-card-icon-color": "#0F172A",
      "columnlink-hover-bg": "#FBFBFB",
      "columnlink-hover-fg": "#5C94FF",
      "columnlink-active-bg": "#FFFFFF",
      "columnlink-active-fg": "#0C0C4F",
      "divider-bg": "#EFEFEF",
      "footer-divider-bg": "#EFEFEF",
      "code-divider-bg": "#313131",
      "footer-stack-bg": "#F6F6F6",
      "navbar-link-bg": "transparent",
      "navbar-link-fg": "#6B7280",
      "navbar-link-hover-bg": "#FBFBFB",
      "navbar-link-hover-fg": "#5C94FF",
      "footer-link-fg": "#858585",
      "footer-header-fg": "#080844",
      "navbar-link-active-bg": "transparent",
      "navbar-link-active-fg": "#2166EF",
      "navbar-link-visited-bg": "transparent",
      "navbar-link-visited-fg": "#2166EF",
      "nav-dialog-bg": "#FBFBFB",
      "nav-header-bg": "#ffffff",
      "nav-accordion-expanded-bg": "#0C0C4F",
      "nav-accordion-expanded-fg": "#FFFFFF",
      "nav-footer-br": "#EFEFEF",
      "nav-searchinput-bg": "#F6F6F6",
      "nav-searchinput-fg": "#858585",
      "nav-searchinput-br": "#F6F6F6",
      "nav-searchinput-hover-br": "#EFEFEF",
      "nav-searchinput-hover-bg": "#F6F6F6",
      "nav-searchinput-hover-fg": "#5C94FF",
      "kbd-bg": "#cccccc",
      "kbd-fg": "#363636",
      "roadmap-availability-state-fg": "#082817",
      "hero-gradient-gradient-a": "#FFDAD6",
      "hero-gradient-gradient-b": "#B6C6FF",
      "heading-hero-gradient-1a": "#0C0C4F",
      "heading-hero-gradient-1b": "#0C0C4F",
      "text-hero-fg": "#000",
      "list-card-lg-title-fg": "#000",
      "list-card-sm-title-fg": "#6B7280",
      "list-card-sm-title-link-fg": "#5C94FF",
      "list-card-lg-desc-fg": "#6B7280",
      "list-card-img-bg": "#000",
      "list-card-icon-fg": "#000",
      "list-card-tag-fg": "#1F2937",
      "list-card-tag-bg": "#F3F4F6",
      "btn-filter-bg": "#F6F6F6",
      "btn-filter-hover-bg": "#F1F1FF",
      "btn-filter-active-bg": "#6B7280",
      "btn-filter-fg": "#6A6A6A",
      "btn-filter-hover-fg": "#0C0C4F",
      "btn-filter-active-fg": "#ffffff",
      "btn-filter-active-hover-fg": "#E5E5F3",
      "btn-filter-active-hover-bg": "#858585",
      "card-link-fg": "#5C94FF",
      "card-link-hover-fg": "#5C94FF",
      "hero-home-bg": "#E5ECED",
      "hero-home-text-fg": "#313131",
      "community-card-border-color": "#E2E8F0",
      "card-orange-bg": "#FDF8F8",
      "card-orange-br": "#F9F0F0",
      "card-blue-bg": "#F6FAFC",
      "card-blue-br": "#F3F6F8",
      "card-yellow-bg": "#FDFBF9",
      "card-yellow-br": "#F7F4F2",
      "card-green-bg": "#F8FCFD",
      "card-green-br": "#EFF6F7",
      "tabs-main-br": "#EFEFEF",
      "tabs-fg": "#858585",
      "tabs-bg": "transparent",
      "tabs-hover-fg": "#858585",
      "tabs-border-bg": "transparent",
      "tabs-fg-active": "#0C0C4F",
      "tabs-border-active-bg": "#E97880",
      "badge-starkstruck-bg": "#D1FAE5",
      "badge-starkstruck-fg": "#1F2937",
      "badge-engineering-bg": "#FEE2E2",
      "badge-engineering-fg": "#991B1B",
      "badge-community-calls-bg": "#FEF3C7",
      "badge-community-calls-fg": "#92400E",
      "badge-tutorials-and-guides-bg": "#FBF2B1",
      "badge-tutorials-and-guides-fg": "#8B7710",
      "badge-stark-math-bg": "#DBEAFE",
      "badge-stark-math-fg": "#1E40AF",
      "badge-governance-bg": "#EDE9FE",
      "badge-governance-fg": "#5B21B6",
      "badge-foundation-fg": "#065F46",
      "badge-community-and-events-bg": "#FCE7F3",
      "badge-community-and-events-fg": "#9D174D",
      "hero-gradient-dapps-a": "#FFDAD6",
      "hero-gradient-dapps-b": "#B6C6FF",
      "hero-gradient-wallets-a": "#FADAAB",
      "hero-gradient-wallets-b": "#ECA9FD",
      "hero-gradient-block-explorers-a": "#B5F6FF",
      "hero-gradient-block-explorers-b": "#FDF4A9",
      "hero-gradient-bridges-on-ramps-a": "#B4DBFF",
      "hero-gradient-bridges-on-ramps-b": "#A9FDB6",
      "hero-gradient-community-a": "#DDC2FF",
      "hero-gradient-community-b": "#FFECCF",
      "hero-gradient-developer-a": "#FFC8CE",
      "hero-gradient-developer-b": "#FDFAA9",
      "hero-gradient-learn-a": "#FFDAD6",
      "hero-gradient-learn-b": "#B6C6FF",
      "hero-gradient-nodes-and-services-a": "#F7E9E8",
      "hero-gradient-nodes-and-services-b": "#CDCEE7",
      "hero-gradient-security-a": "#C4D7FF",
      "hero-gradient-security-b": "#F3CDFF",
      "hero-subtitle-fg": "#313131",
      "btn-outline-hero-bg": "transparent",
      "btn-outline-hero-fg": "#0C0C4F",
      "btn-outline-hero-border": "#0C0C4F",
      "btn-outline-hero-hover-bg": "rgba(255, 255, 255, 0.5)",
      "btn-outline-hero-hover-fg": "#5C94FF",
      "btn-outline-hero-hover-border": "##5C94FF",
      "btn-outline-hero-active-bg": "rgba(0, 0, 0, 0.05)",
      "btn-outline-hero-active-fg": "#5C94FF",
      "btn-outline-hero-active-border": "#5C94FF",
      "btn-primary-hero-bg": "#0C0C4F",
      "btn-primary-hero-hover-bg": "#5C94FF",
      "btn-primary-hero-active-bg": "#4A76CC",
      "btn-primary-hero-fg": "#FFFFFF",
      "btn-primary-hero-hover-fg": "#FFFFFF",
      "btn-primary-hero-active-fg": "#FFFFFF",
      "btn-primary-hero-border": "#0C0C4F",
      "btn-primary-hero-hover-border": "#0C0C4F",
      "btn-primary-hero-active-border": "#5C94FF",
      "gradient-orange-a": "#FAE4AB",
      "gradient-orange-b": "#F6D0C7",
      "gradient-blue-a": "#B4DCFE",
      "gradient-blue-b": " #B0E7E6 ",
      "gradient-purple-a": " #DDC2FF",
      "gradient-purple-b": "#FFECCF",
      "gradient-peach-a": " #FFC8CF  ",
      "gradient-peach-b": "  #FFDBC1 ",
      "gradient-cyan-a": " #B6F7FF  ",
      "gradient-cyan-b": "  #CCF6E3",
      "gradient-pink-a": " #FFDAD7 ",
      "gradient-pink-b": "  #E8D4E3",
      "gradient-blue-default-a": " #E9F2F8 ",
      "gradient-blue-default-b": "  #FBF6F1",
      "roadmap-card-border-color": "#CCCCCC",
      "roadmap-card-tag-border-color": "#DDDDDD",
      "roadmap-card-bg-color": "#FFFFFF",
      "roadmap-card-tag-bg": "#ffffff",
      "summit-popup-date-heading-color": "#D672EF",
      "councils-title-fg": "#1F1F1F"
    },

    dark: {
      "listLink-fg": "#AFCAFF",
      "bg-default": "#0B0B0B",
      "fg-default": "#CCCCCC",
      "fg-muted": "#7E7E7E",
      "fg-accent": "#FE9E92",
      "navbar-bg": "#121212",
      "navbar-dropdown-bg": "#1B1B1B",
      "button-nav-bg": "transparent",
      "button-nav-fg": "#FFFFFF",
      "button-nav-icon-fg": "#7E7E7E",
      "button-nav-hover-bg": "#000000",
      "button-nav-hover-fg": "#FFFFFF",
      "button-nav-hover-icon-fg": "#AFCAFF",
      "button-nav-active-bg": "#000000",
      "button-nav-active-fg": "#7E7E7E",
      "button-nav-active-icon-fg": "#7E7E7E",
      "button-nav-focus-br": "#AFCAFF",
      "btn-outline-bg": "transparent",
      "btn-outline-fg": "#ffffff",
      "btn-outline-border": "#7E7E7E",
      "btn-outline-hover-bg": "transparent",
      "btn-outline-hover-fg": "#9EBFFF",
      "btn-outline-hover-border": "#9EBFFF",
      "btn-outline-active-bg": "#000000",
      "btn-outline-active-fg": "#858585",
      "btn-outline-active-border": "#000000",

      "btn-bg": "",
      "btn-hover-bg": "",
      "btn-active-bg": "",
      "btn-fg": "",
      "btn-hover-fg": "",
      "btn-active-fg": "",
      "btn-border": "",
      "btn-hover-border": "",
      "btn-active-border": "",
      "btn-primary-bg": "#5C94FF",
      "btn-primary-hover-bg": "#5C94FF",
      "btn-primary-active-bg": "#5C94FF",
      "btn-primary-fg": "#FFFFFF",
      "btn-primary-hover-fg": "#FFFFFF",
      "btn-primary-active-fg": "#FFFFFF",
      "btn-primary-border": "#5C94FF",
      "btn-primary-hover-border": "#5C94FF",
      "btn-primary-active-border": "#5C94FF",
      "article-card-bg": "#1B1B1B",
      "card-bg": "#1B1B1B",
      "roadmap-hero-card-bg": "#1B1B1B",
      "roadmap-hero-gradient": "linear-gradient(259.71deg, #414548 2.88%, #1C1D24 96.77%)",
      "roadmap-hero-arrow-gradient": "linear(45deg, #82BDBD 100%, #4F6D87 100%)",
      "card-br": "#000000",
      "subnav-fg": "#7E7E7E",
      "subnav-fg-accent": "#ffffff",
      "heading-navy-fg": "#FFFFFF",
      "columnlink-bg": "transparent",
      "columnlink-fg": "#CCCCCC",
      "tutorials-card-icon-color": "#FFFFFF",
      "columnlink-hover-bg": "#121212",
      "columnlink-hover-fg": "#9EBFFF",
      "columnlink-active-bg": "transparent",
      "columnlink-active-fg": "#9EBFFF",
      "divider-bg": "#313131",
      "footer-divider-bg": "#313131",
      "code-divider-bg": "#CCCCCC",
      "navbar-link-bg": "transparent",
      "navbar-link-fg": "#CCCCCC",
      "navbar-link-hover-bg": "#121212",
      "navbar-link-hover-fg": "#9EBFFF",
      "footer-link-fg": "#858585",
      "footer-header-fg": "#ffffff",
      "footer-stack-bg": "#0B0B0B",
      "navbar-link-active-bg": "transparent",
      "navbar-link-active-fg": "#2166EF",
      "navbar-link-visited-bg": "transparent",
      "navbar-link-visited-fg": "#2166EF",
      "nav-dialog-bg": "#1B1B1B",
      "nav-header-bg": "#000000",
      "nav-accordion-expanded-bg": "#AFCAFF",
      "nav-accordion-expanded-fg": "#121212",
      "nav-footer-br": "#313131",
      "nav-searchinput-bg": "#1B1B1B",
      "nav-searchinput-fg": "#AFCAFF",
      "nav-searchinput-br": "#1B1B1B",
      "nav-searchinput-hover-br": "#858585",
      "nav-searchinput-hover-bg": "#000000",
      "nav-searchinput-hover-fg": "#AFCAFF",
      "kbd-bg": "#313131",
      "kbd-fg": "#CCCCCC",
      "roadmap-availability-state-fg": "#FFFFFF",
      "heading-hero-gradient-1a": "#D672EF",
      "heading-hero-gradient-1b": "#EC796B",
      "hero-gradient-1a": "#171B31",
      "hero-gradient-1b": "#213033",
      "text-hero-fg": "#FFFFFF",
      "list-card-lg-title-fg": "#FFFFFF",
      "list-card-sm-title-fg": "#CCCCCC",
      "list-card-sm-title-link-fg": "#AFCAFF",
      "community-card-border-color": "#313131",
      "roadmap-card-bg-color": "#313131",
      "list-card-lg-desc-fg": "#CCCCCC",
      "list-card-img-bg": "#000",
      "list-card-icon-fg": "#FFFFFF",
      "list-card-tag-fg": "#1F2937",
      "list-card-tag-bg": "#F3F4F6",
      "btn-filter-bg": "#1B1B1B",
      "btn-filter-hover-bg": "#363636",
      "btn-filter-active-bg": "#9EBFFF",
      "btn-filter-fg": "#CCCCCC",
      "btn-filter-hover-fg": "#CCCCCC",
      "btn-filter-active-fg": "#121212",
      "btn-filter-active-hover-fg": "#0B0B0B",
      "btn-filter-active-hover-bg": "#B2CDFF",
      "card-link-fg": "#AFCAFF",
      "card-link-hover-fg": "#AFCAFF",
      "hero-home-bg": "#000000",
      "hero-home-text-fg": "#121212",
      "card-orange-bg": "#161616",
      "card-orange-br": "#121212",
      "card-blue-bg": "#161616",
      "card-blue-br": "#121212",
      "card-yellow-bg": "#161616",
      "card-yellow-br": "#121212",
      "card-green-bg": "#161616",
      "card-green-br": "#121212",
      "tabs-main-br": "#1E1D1D",
      "tabs-fg": "#7E7E7E",
      "tabs-bg": "transparent",
      "tabs-hover-fg": "#CCCCCC",
      "tabs-border-bg": "transparent",
      "tabs-fg-active": "#FFFFFF",
      "tabs-border-active-bg": "#FE9E92",
      "badge-starkstruck-bg": "#D1FAE5",
      "badge-starkstruck-fg": "#1F2937",
      "badge-engineering-bg": "#FEE2E2",
      "badge-engineering-fg": "#991B1B",
      "badge-community-calls-bg": "#FEF3C7",
      "badge-community-calls-fg": "#92400E",
      "badge-tutorials-and-guides-bg": "#FBF2B1",
      "badge-tutorials-and-guides-fg": "#8B7710",
      "badge-stark-math-bg": "#DBEAFE",
      "badge-stark-math-fg": "#1E40AF",
      "badge-governance-bg": "#EDE9FE",
      "badge-governance-fg": "#5B21B6",
      "badge-foundation-fg": "#065F46",
      "badge-community-and-events-bg": "#FCE7F3",
      "badge-community-and-events-fg": "#9D174D",
      "hero-gradient-dapps-a": "#50465C",
      "hero-gradient-dapps-b": "#171B31",
      "hero-gradient-wallets-a": "#3C3224",
      "hero-gradient-wallets-b": "#171B31",
      "hero-gradient-block-explorers-a": "#364B4E",
      "hero-gradient-block-explorers-b": "#171B31",
      "hero-gradient-bridges-on-ramps-a": "#3E4E5B",
      "hero-gradient-bridges-on-ramps-b": "#171B31",
      "hero-gradient-community-a": "#50465C",
      "hero-gradient-community-b": "#171B31",
      "hero-gradient-developer-a": "#63494B",
      "hero-gradient-developer-b": "#171B31",
      "hero-gradient-learn-a": "#213033",
      "hero-gradient-learn-b": "#171B31",
      "hero-gradient-nodes-and-services-a": "#664E79",
      "hero-gradient-nodes-and-services-b": "#1A1628",
      "hero-gradient-security-a": "#143B75",
      "hero-gradient-security-b": "#0C0F32",
      "hero-subtitle-fg": "#CCCCCC",
      "btn-outline-hero-bg": "transparent",
      "btn-outline-hero-fg": "#ffffff",
      "btn-outline-hero-border": "#FFFFFF",
      "btn-outline-hero-hover-bg": "rgba(0, 0, 0, 0.2)",
      "btn-outline-hero-hover-fg": "#AFCAFF",
      "btn-outline-hero-hover-border": "#AFCAFF",
      "btn-outline-hero-active-bg": "rgba(0, 0, 0, 0.4)",
      "btn-outline-hero-active-fg": "#AFCAFF",
      "btn-outline-hero-active-border": "#AFCAFF",
      "btn-primary-hero-bg": "#FFFFFF",
      "btn-primary-hero-hover-bg": "#AFCAFF",
      "btn-primary-hero-active-bg": "#8CA2CC",
      "btn-primary-hero-fg": "#0C0C4F",
      "btn-primary-hero-hover-fg": "#0C0C4F",
      "btn-primary-hero-active-fg": "#0C0C4F",
      "btn-primary-hero-border": "#5C94FF",
      "btn-primary-hero-hover-border": "#5C94FF",
      "btn-primary-hero-active-border": "#5C94FF",
      "gradient-orange-a": "#202134",
      "gradient-orange-b": "#63494B",
      "gradient-blue-a": "#1B2035",
      "gradient-blue-b": " #3E4F5C ",
      "gradient-purple-a": " #51465D",
      "gradient-purple-b": "#1C1F34",
      "gradient-peach-a": " #1B1D30  ",
      "gradient-peach-b": "  #3B3225 ",
      "gradient-cyan-a": " #364B4E  ",
      "gradient-cyan-b": "  #1B2034",
      "gradient-pink-a": " #191E31 ",
      "gradient-pink-b": "  #223033",
      "gradient-blue-default-a": " #252525 ",
      "gradient-blue-default-b": "  #1B1B1B",
      "roadmap-card-border-color": "#5C5C5C",
      "roadmap-card-tag-border-color": "#5C5C5C",
      "roadmap-card-tag-bg": "#313131",
      "summit-popup-date-heading-color": "#D672EF",
      "councils-title-fg": "#FFFFFF"
    },
  },
};

export const semanticTokens = {
  colors: {
    "listLink-fg": {
      default: tokens.colors.light["listLink-fg"],
      _dark: tokens.colors.dark["listLink-fg"],
    },
    "bg-default": {
      default: tokens.colors.light["bg-default"],
      _dark: tokens.colors.dark["bg-default"],
    },
    "fg-default": {
      default: tokens.colors.light["fg-default"],
      _dark: tokens.colors.dark["fg-default"],
    },
    "fg-muted": {
      default: tokens.colors.light["fg-muted"],
      _dark: tokens.colors.dark["fg-muted"],
    },
    "fg-accent": {
      default: tokens.colors.light["fg-accent"],
      _dark: tokens.colors.dark["fg-accent"],
    },
    "navbar-bg": {
      default: tokens.colors.light["navbar-bg"],
      _dark: tokens.colors.dark["navbar-bg"],
    },
    "navbar-dropdown-bg": {
      default: tokens.colors.light["navbar-dropdown-bg"],
      _dark: tokens.colors.dark["navbar-dropdown-bg"],
    },
    // "navlink-fg": {
    //   default: tokens.colors.light["navlink-fg"],
    //   _dark: tokens.colors.dark["navlink-fg"],
    // },
    "btn-bg": {
      default: tokens.colors.light["btn-bg"],
      _dark: tokens.colors.dark["btn-bg"],
    },
    "btn-hover-bg": {
      default: tokens.colors.light["btn-hover-bg"],
      _dark: tokens.colors.dark["btn-hover-bg"],
    },
    "btn-active-bg": {
      default: tokens.colors.light["btn-active-bg"],
      _dark: tokens.colors.dark["btn-active-bg"],
    },
    "btn-fg": {
      default: tokens.colors.light["btn-fg"],
      _dark: tokens.colors.dark["btn-fg"],
    },
    "btn-hover-fg": {
      default: tokens.colors.light["btn-hover-fg"],
      _dark: tokens.colors.dark["btn-hover-fg"],
    },
    "btn-active-fg": {
      default: tokens.colors.light["btn-active-fg"],
      _dark: tokens.colors.dark["btn-active-fg"],
    },
    "btn-border": {
      default: tokens.colors.light["btn-border"],
      _dark: tokens.colors.dark["btn-border"],
    },
    "btn-hover-border": {
      default: tokens.colors.light["btn-hover-border"],
      _dark: tokens.colors.dark["btn-hover-border"],
    },
    "btn-active-border": {
      default: tokens.colors.light["btn-active-border"],
      _dark: tokens.colors.dark["btn-active-border"],
    },

    "btn-primary-bg": {
      default: tokens.colors.light["btn-primary-bg"],
      _dark: tokens.colors.dark["btn-primary-bg"],
    },
    "btn-primary-hover-bg": {
      default: tokens.colors.light["btn-primary-hover-bg"],
      _dark: tokens.colors.dark["btn-primary-hover-bg"],
    },
    "btn-primary-active-bg": {
      default: tokens.colors.light["btn-primary-active-bg"],
      _dark: tokens.colors.dark["btn-primary-active-bg"],
    },
    "btn-primary-fg": {
      default: tokens.colors.light["btn-primary-fg"],
      _dark: tokens.colors.dark["btn-primary-fg"],
    },
    "btn-primary-hover-fg": {
      default: tokens.colors.light["btn-primary-hover-fg"],
      _dark: tokens.colors.dark["btn-primary-hover-fg"],
    },
    "btn-primary-active-fg": {
      default: tokens.colors.light["btn-primary-active-fg"],
      _dark: tokens.colors.dark["btn-primary-active-fg"],
    },
    "btn-primary-border": {
      default: tokens.colors.light["btn-primary-border"],
      _dark: tokens.colors.dark["btn-primary-border"],
    },
    "btn-primary-hover-border": {
      default: tokens.colors.light["btn-primary-hover-border"],
      _dark: tokens.colors.dark["btn-primary-hover-border"],
    },
    "btn-primary-active-border": {
      default: tokens.colors.light["btn-primary-active-border"],
      _dark: tokens.colors.dark["btn-primary-active-border"],
    },
    "article-card-bg": {
      default: tokens.colors.light["article-card-bg"],
      _dark: tokens.colors.dark["article-card-bg"],
    },
    "card-bg": {
      default: tokens.colors.light["card-bg"],
      _dark: tokens.colors.dark["card-bg"],
    },
    "roadmap-hero-card-bg": {
      default: tokens.colors.light["roadmap-hero-card-bg"],
      _dark: tokens.colors.dark["roadmap-hero-card-bg"],
    },
    "roadmap-hero-gradient": {
      default: tokens.colors.light["roadmap-hero-gradient"],
      _dark: tokens.colors.dark["roadmap-hero-gradient"],
    },
    "roadmap-hero-arrow-gradient": {
      default: tokens.colors.light["roadmap-hero-arrow-gradient"],
      _dark: tokens.colors.dark["roadmap-hero-arrow-gradient"],
    },
    "card-br": {
      default: tokens.colors.light["card-br"],
      _dark: tokens.colors.dark["card-br"],
    },
    "subnav-fg": {
      default: tokens.colors.light["subnav-fg"],
      _dark: tokens.colors.dark["subnav-fg"],
    },
    "subnav-fg-accent": {
      default: tokens.colors.light["subnav-fg-accent"],
      _dark: tokens.colors.dark["subnav-fg-accent"],
    },
    "heading-navy-fg": {
      default: tokens.colors.light["heading-navy-fg"],
      _dark: tokens.colors.dark["heading-navy-fg"],
    },
    "columnlink-bg": {
      default: tokens.colors.light["columnlink-bg"],
      _dark: tokens.colors.dark["columnlink-bg"],
    },
    "columnlink-fg": {
      default: tokens.colors.light["columnlink-fg"],
      _dark: tokens.colors.dark["columnlink-fg"],
    },
    "tutorials-card-icon-color": {
      default: tokens.colors.light["tutorials-card-icon-color"],
      _dark: tokens.colors.dark["tutorials-card-icon-color"],
    },
    "columnlink-hover-bg": {
      default: tokens.colors.light["columnlink-hover-bg"],
      _dark: tokens.colors.dark["columnlink-hover-bg"],
    },
    "columnlink-hover-fg": {
      default: tokens.colors.light["columnlink-hover-fg"],
      _dark: tokens.colors.dark["columnlink-hover-fg"],
    },
    "columnlink-active-bg": {
      default: tokens.colors.light["columnlink-active-bg"],
      _dark: tokens.colors.dark["columnlink-active-bg"],
    },
    "columnlink-active-fg": {
      default: tokens.colors.light["columnlink-active-fg"],
      _dark: tokens.colors.dark["columnlink-active-fg"],
    },
    "btn-outline-bg": {
      default: tokens.colors.light["btn-outline-bg"],
      _dark: tokens.colors.dark["btn-outline-bg"],
    },
    "btn-outline-fg": {
      default: tokens.colors.light["btn-outline-fg"],
      _dark: tokens.colors.dark["btn-outline-fg"],
    },
    "btn-outline-border": {
      default: tokens.colors.light["btn-outline-border"],
      _dark: tokens.colors.dark["btn-outline-border"],
    },
    "btn-outline-hover-border": {
      default: tokens.colors.light["btn-outline-hover-border"],
      _dark: tokens.colors.dark["btn-outline-hover-border"],
    },
    "btn-outline-hover-fg": {
      default: tokens.colors.light["btn-outline-hover-fg"],
      _dark: tokens.colors.dark["btn-outline-hover-fg"],
    },
    "btn-outline-active-bg": {
      default: tokens.colors.light["btn-outline-active-bg"],
      _dark: tokens.colors.dark["btn-outline-active-bg"],
    },
    "btn-outline-active-fg": {
      default: tokens.colors.light["btn-outline-active-fg"],
      _dark: tokens.colors.dark["btn-outline-active-fg"],
    },
    "btn-outline-active-border": {
      default: tokens.colors.light["btn-outline-active-border"],
      _dark: tokens.colors.dark["btn-outline-active-border"],
    },
    "navbar-link-bg": {
      default: tokens.colors.light["navbar-link-bg"],
      _dark: tokens.colors.dark["navbar-link-bg"],
    },
    "navbar-link-fg": {
      default: tokens.colors.light["navbar-link-fg"],
      _dark: tokens.colors.dark["navbar-link-fg"],
    },
    "navbar-link-hover-bg": {
      default: tokens.colors.light["navbar-link-hover-bg"],
      _dark: tokens.colors.dark["navbar-link-hover-bg"],
    },
    "navbar-link-active-bg": {
      default: tokens.colors.light["navbar-link-active-bg"],
      _dark: tokens.colors.dark["navbar-link-active-bg"],
    },
    "navbar-link-hover-fg": {
      default: tokens.colors.light["navbar-link-hover-fg"],
      _dark: tokens.colors.dark["navbar-link-hover-fg"],
    },
    "footer-link-fg": {
      default: tokens.colors.light["footer-link-fg"],
      _dark: tokens.colors.dark["footer-link-fg"],
    },
    "footer-header-fg": {
      default: tokens.colors.light["footer-header-fg"],
      _dark: tokens.colors.dark["footer-header-fg"],
    },
    "navbar-link-active-fg": {
      default: tokens.colors.light["navbar-link-active-fg"],
      _dark: tokens.colors.dark["navbar-link-active-fg"],
    },
    "navbar-link-visited-bg": {
      default: tokens.colors.light["navbar-link-visited-bg"],
      _dark: tokens.colors.dark["navbar-link-visited-bg"],
    },
    "navbar-link-visited-fg": {
      default: tokens.colors.light["navbar-link-visited-fg"],
      _dark: tokens.colors.dark["navbar-link-visited-fg"],
    },
    "nav-dialog-bg": {
      default: tokens.colors.light["nav-dialog-bg"],
      _dark: tokens.colors.dark["nav-dialog-bg"],
    },
    "nav-header-bg": {
      default: tokens.colors.light["nav-header-bg"],
      _dark: tokens.colors.dark["nav-header-bg"],
    },
    "nav-accordion-expanded-bg": {
      default: tokens.colors.light["nav-accordion-expanded-bg"],
      _dark: tokens.colors.dark["nav-accordion-expanded-bg"],
    },
    "nav-accordion-expanded-fg": {
      default: tokens.colors.light["nav-accordion-expanded-fg"],
      _dark: tokens.colors.dark["nav-accordion-expanded-fg"],
    },
    "nav-footer-br": {
      default: tokens.colors.light["nav-footer-br"],
      _dark: tokens.colors.dark["nav-footer-br"],
    },
    "nav-searchinput-bg": {
      default: tokens.colors.light["nav-searchinput-bg"],
      _dark: tokens.colors.dark["nav-searchinput-bg"],
    },
    "nav-searchinput-fg": {
      default: tokens.colors.light["nav-searchinput-fg"],
      _dark: tokens.colors.dark["nav-searchinput-fg"],
    },
    "nav-searchinput-hover-bg": {
      default: tokens.colors.light["nav-searchinput-hover-bg"],
      _dark: tokens.colors.dark["nav-searchinput-hover-bg"],
    },
    "nav-searchinput-hover-fg": {
      default: tokens.colors.light["nav-searchinput-hover-fg"],
      _dark: tokens.colors.dark["nav-searchinput-hover-fg"],
    },
    "nav-searchinput-br": {
      default: tokens.colors.light["nav-searchinput-br"],
      _dark: tokens.colors.dark["nav-searchinput-br"],
    },
    "nav-searchinput-hover-br": {
      default: tokens.colors.light["nav-searchinput-hover-br"],
      _dark: tokens.colors.dark["nav-searchinput-hover-br"],
    },
    "kbd-bg": {
      default: tokens.colors.light["kbd-bg"],
      _dark: tokens.colors.dark["kbd-bg"],
    },
    "kbd-fg": {
      default: tokens.colors.light["kbd-fg"],
      _dark: tokens.colors.dark["kbd-fg"],
    },
    "roadmap-availability-state-fg": {
      default: tokens.colors.light["roadmap-availability-state-fg"],
      _dark: tokens.colors.dark["roadmap-availability-state-fg"],
    },
    "button-nav-bg": {
      default: tokens.colors.light["button-nav-bg"],
      _dark: tokens.colors.dark["button-nav-bg"],
    },
    "button-nav-fg": {
      default: tokens.colors.light["button-nav-fg"],
      _dark: tokens.colors.dark["button-nav-fg"],
    },
    "button-nav-icon-fg": {
      default: tokens.colors.light["button-nav-icon-fg"],
      _dark: tokens.colors.dark["button-nav-icon-fg"],
    },
    "button-nav-hover-bg": {
      default: tokens.colors.light["button-nav-hover-bg"],
      _dark: tokens.colors.dark["button-nav-hover-bg"],
    },
    "button-nav-hover-fg": {
      default: tokens.colors.light["button-nav-hover-fg"],
      _dark: tokens.colors.dark["button-nav-hover-fg"],
    },
    "button-nav-hover-icon-fg": {
      default: tokens.colors.light["button-nav-hover-icon-fg"],
      _dark: tokens.colors.dark["button-nav-hover-icon-fg"],
    },
    "button-nav-active-bg": {
      default: tokens.colors.light["button-nav-active-bg"],
      _dark: tokens.colors.dark["button-nav-active-bg"],
    },
    "button-nav-active-fg": {
      default: tokens.colors.light["button-nav-active-fg"],
      _dark: tokens.colors.dark["button-nav-active-fg"],
    },
    "button-nav-active-icon-fg": {
      default: tokens.colors.light["button-nav-active-icon-fg"],
      _dark: tokens.colors.dark["button-nav-active-icon-fg"],
    },
    "button-nav-focus-br": {
      default: tokens.colors.light["button-nav-focus-br"],
      _dark: tokens.colors.dark["button-nav-focus-br"],
    },
    "divider-bg": {
      default: tokens.colors.light["divider-bg"],
      _dark: tokens.colors.dark["divider-bg"],
    },
    "footer-divider-bg": {
      default: tokens.colors.light["footer-divider-bg"],
      _dark: tokens.colors.dark["footer-divider-bg"],
    },
    "code-divider-bg": {
      default: tokens.colors.light["code-divider-bg"],
      _dark: tokens.colors.dark["code-divider-bg"],
    },
    // "hero-gradient-1a": {
    //   default: tokens.colors.light["hero-gradient-1a"],
    //   _dark: tokens.colors.dark["hero-gradient-1a"],
    // },
    // "hero-gradient-1b": {
    //   default: tokens.colors.light["hero-gradient-1b"],
    //   _dark: tokens.colors.dark["hero-gradient-1b"],
    // },
    "heading-hero-gradient-1b": {
      default: tokens.colors.light["heading-hero-gradient-1b"],
      _dark: tokens.colors.dark["heading-hero-gradient-1b"],
    },
    "heading-hero-gradient-1a": {
      default: tokens.colors.light["heading-hero-gradient-1b"],
      _dark: tokens.colors.dark["heading-hero-gradient-1b"],
    },
    "text-hero-fg": {
      default: tokens.colors.light["text-hero-fg"],
      _dark: tokens.colors.dark["text-hero-fg"],
    },
    "list-card-lg-title-fg": {
      default: tokens.colors.light["list-card-lg-title-fg"],
      _dark: tokens.colors.dark["list-card-lg-title-fg"],
    },
    "list-card-sm-title-fg": {
      default: tokens.colors.light["list-card-sm-title-fg"],
      _dark: tokens.colors.dark["list-card-sm-title-fg"],
    },
    "list-card-sm-title-link-fg": {
      default: tokens.colors.light["list-card-sm-title-link-fg"],
      _dark: tokens.colors.dark["list-card-sm-title-link-fg"],
    },
    "list-card-lg-desc-fg": {
      default: tokens.colors.light["list-card-lg-desc-fg"],
      _dark: tokens.colors.dark["list-card-lg-desc-fg"],
    },
    "list-card-img-bg": {
      default: tokens.colors.light["list-card-img-bg"],
      _dark: tokens.colors.dark["list-card-img-bg"],
    },
    "list-card-icon-fg": {
      default: tokens.colors.light["list-card-icon-fg"],
      _dark: tokens.colors.dark["list-card-icon-fg"],
    },
    "list-card-tag-fg": {
      default: tokens.colors.light["list-card-tag-fg"],
      _dark: tokens.colors.dark["list-card-tag-fg"],
    },
    "list-card-tag-bg": {
      default: tokens.colors.light["list-card-tag-bg"],
      _dark: tokens.colors.dark["list-card-tag-bg"],
    },
    "btn-filter-bg": {
      default: tokens.colors.light["btn-filter-bg"],
      _dark: tokens.colors.dark["btn-filter-bg"],
    },
    "btn-filter-hover-bg": {
      default: tokens.colors.light["btn-filter-hover-bg"],
      _dark: tokens.colors.dark["btn-filter-hover-bg"],
    },
    "btn-filter-active-bg": {
      default: tokens.colors.light["btn-filter-active-bg"],
      _dark: tokens.colors.dark["btn-filter-active-bg"],
    },
    "btn-filter-fg": {
      default: tokens.colors.light["btn-filter-fg"],
      _dark: tokens.colors.dark["btn-filter-fg"],
    },
    "btn-filter-hover-fg": {
      default: tokens.colors.light["btn-filter-hover-fg"],
      _dark: tokens.colors.dark["btn-filter-hover-fg"],
    },
    "btn-filter-active-fg": {
      default: tokens.colors.light["btn-filter-active-fg"],
      _dark: tokens.colors.dark["btn-filter-active-fg"],
    },
    "btn-filter-active-hover-fg": {
      default: tokens.colors.light["btn-filter-active-hover-fg"],
      _dark: tokens.colors.dark["btn-filter-active-hover-fg"],
    },
    "btn-filter-active-hover-bg": {
      default: tokens.colors.light["btn-filter-active-hover-bg"],
      _dark: tokens.colors.dark["btn-filter-active-hover-bg"],
    },
    "card-link-fg": {
      default: tokens.colors.light["card-link-fg"],
      _dark: tokens.colors.dark["card-link-fg"],
    },
    "card-link-hover-fg": {
      default: tokens.colors.light["card-link-hover-fg"],
      _dark: tokens.colors.dark["card-link-hover-fg"],
    },
    "hero-home-bg": {
      default: tokens.colors.light["hero-home-bg"],
      _dark: tokens.colors.dark["hero-home-bg"],
    },
    "hero-home-text-fg": {
      default: tokens.colors.light["hero-home-text-fg"],
      _dark: tokens.colors.dark["hero-home-text-fg"],
    },
    "card-orange-bg": {
      default: tokens.colors.light["card-orange-bg"],
      _dark: tokens.colors.dark["card-orange-bg"],
    },
    "card-orange-br": {
      default: tokens.colors.light["card-orange-br"],
      _dark: tokens.colors.dark["card-orange-br"],
    },
    "card-green-bg": {
      default: tokens.colors.light["card-green-bg"],
      _dark: tokens.colors.dark["card-green-bg"],
    },
    "card-yellow-br": {
      default: tokens.colors.light["card-yellow-br"],
      _dark: tokens.colors.dark["card-yellow-br"],
    },
    "card-yellow-bg": {
      default: tokens.colors.light["card-yellow-bg"],
      _dark: tokens.colors.dark["card-yellow-bg"],
    },
    "card-green-br": {
      default: tokens.colors.light["card-green-br"],
      _dark: tokens.colors.dark["card-green-br"],
    },
    "card-blue-bg": {
      default: tokens.colors.light["card-blue-bg"],
      _dark: tokens.colors.dark["card-blue-bg"],
    },
    "card-blue-br": {
      default: tokens.colors.light["card-blue-br"],
      _dark: tokens.colors.dark["card-blue-br"],
    },
    "tabs-main-br": {
      default: tokens.colors.light["tabs-main-br"],
      _dark: tokens.colors.dark["tabs-main-br"],
    },
    "tabs-fg": {
      default: tokens.colors.light["tabs-fg"],
      _dark: tokens.colors.dark["tabs-fg"],
    },
    "tabs-bg": {
      default: tokens.colors.light["tabs-bg"],
      _dark: tokens.colors.dark["tabs-bg"],
    },
    "tabs-hover-fg": {
      default: tokens.colors.light["tabs-hover-fg"],
      _dark: tokens.colors.dark["tabs-hover-fg"],
    },
    "tabs-border-bg": {
      default: tokens.colors.light["tabs-border-bg"],
      _dark: tokens.colors.dark["tabs-border-bg"],
    },
    "tabs-fg-active": {
      default: tokens.colors.light["tabs-fg-active"],
      _dark: tokens.colors.dark["tabs-fg-active"],
    },
    "tabs-border-active-bg": {
      default: tokens.colors.light["tabs-border-active-bg"],
      _dark: tokens.colors.dark["tabs-border-active-bg"],
    },
    "badge-starkstruck-bg": {
      default: tokens.colors.light["badge-starkstruck-bg"],
      _dark: tokens.colors.dark["badge-starkstruck-bg"],
    },
    "badge-starkstruck-fg": {
      default: tokens.colors.light["badge-starkstruck-fg"],
      _dark: tokens.colors.dark["badge-starkstruck-fg"],
    },
    "badge-foundation-fg": {
      default: tokens.colors.light["badge-foundation-fg"],
      _dark: tokens.colors.dark["badge-foundation-fg"],
    },
    "badge-engineering-bg": {
      default: tokens.colors.light["badge-engineering-bg"],
      _dark: tokens.colors.dark["badge-engineering-bg"],
    },
    "badge-engineering-fg": {
      default: tokens.colors.light["badge-engineering-fg"],
      _dark: tokens.colors.dark["badge-engineering-fg"],
    },
    "badge-community-calls-bg": {
      default: tokens.colors.light["badge-community-calls-bg"],
      _dark: tokens.colors.dark["badge-community-calls-bg"],
    },
    "badge-community-calls-fg": {
      default: tokens.colors.light["badge-community-calls-fg"],
      _dark: tokens.colors.dark["badge-community-calls-fg"],
    },
    "badge-tutorials-and-guides-bg": {
      default: tokens.colors.light["badge-tutorials-and-guides-bg"],
      _dark: tokens.colors.dark["badge-tutorials-and-guides-bg"],
    },
    "badge-tutorials-and-guides-fg": {
      default: tokens.colors.light["badge-tutorials-and-guides-fg"],
      _dark: tokens.colors.dark["badge-tutorials-and-guides-fg"],
    },
    "badge-stark-math-bg": {
      default: tokens.colors.light["badge-stark-math-bg"],
      _dark: tokens.colors.dark["badge-stark-math-bg"],
    },
    "badge-stark-math-fg": {
      default: tokens.colors.light["badge-stark-math-fg"],
      _dark: tokens.colors.dark["badge-stark-math-fg"],
    },
    "badge-governance-bg": {
      default: tokens.colors.light["badge-governance-bg"],
      _dark: tokens.colors.dark["badge-governance-bg"],
    },
    "badge-governance-fg": {
      default: tokens.colors.light["badge-governance-fg"],
      _dark: tokens.colors.dark["badge-governance-fg"],
    },
    "badge-community-and-events-bg": {
      default: tokens.colors.light["badge-community-and-events-bg"],
      _dark: tokens.colors.dark["badge-community-and-events-bg"],
    },
    "badge-community-and-events-fg": {
      default: tokens.colors.light["badge-community-and-events-fg"],
      _dark: tokens.colors.dark["badge-community-and-events-fg"],
    },
    "hero-gradient-dapps-a": {
      default: tokens.colors.light["hero-gradient-dapps-a"],
      _dark: tokens.colors.dark["hero-gradient-dapps-a"],
    },
    "hero-gradient-dapps-b": {
      default: tokens.colors.light["hero-gradient-dapps-b"],
      _dark: tokens.colors.dark["hero-gradient-dapps-b"],
    },
    "hero-gradient-wallets-a": {
      default: tokens.colors.light["hero-gradient-wallets-a"],
      _dark: tokens.colors.dark["hero-gradient-wallets-a"],
    },
    "hero-gradient-wallets-b": {
      default: tokens.colors.light["hero-gradient-wallets-b"],
      _dark: tokens.colors.dark["hero-gradient-wallets-b"],
    },
    "hero-gradient-block-explorers-a": {
      default: tokens.colors.light["hero-gradient-block-explorers-a"],
      _dark: tokens.colors.dark["hero-gradient-block-explorers-a"],
    },
    "hero-gradient-block-explorers-b": {
      default: tokens.colors.light["hero-gradient-block-explorers-b"],
      _dark: tokens.colors.dark["hero-gradient-block-explorers-b"],
    },
    "hero-gradient-bridges-on-ramps-a": {
      default: tokens.colors.light["hero-gradient-bridges-on-ramps-a"],
      _dark: tokens.colors.dark["hero-gradient-bridges-on-ramps-a"],
    },
    "hero-gradient-bridges-on-ramps-b": {
      default: tokens.colors.light["hero-gradient-bridges-on-ramps-b"],
      _dark: tokens.colors.dark["hero-gradient-bridges-on-ramps-b"],
    },
    "hero-gradient-community-a": {
      default: tokens.colors.light["hero-gradient-community-a"],
      _dark: tokens.colors.dark["hero-gradient-community-a"],
    },
    "hero-gradient-community-b": {
      default: tokens.colors.light["hero-gradient-community-b"],
      _dark: tokens.colors.dark["hero-gradient-community-b"],
    },
    "hero-gradient-developer-a": {
      default: tokens.colors.light["hero-gradient-developer-a"],
      _dark: tokens.colors.dark["hero-gradient-developer-a"],
    },
    "hero-gradient-developer-b": {
      default: tokens.colors.light["hero-gradient-developer-b"],
      _dark: tokens.colors.dark["hero-gradient-developer-b"],
    },
    "hero-gradient-learn-a": {
      default: tokens.colors.light["hero-gradient-learn-a"],
      _dark: tokens.colors.dark["hero-gradient-learn-a"],
    },
    "hero-gradient-learn-b": {
      default: tokens.colors.light["hero-gradient-learn-b"],
      _dark: tokens.colors.dark["hero-gradient-learn-b"],
    },
    "hero-gradient-nodes-and-services-a": {
      default: tokens.colors.light["hero-gradient-nodes-and-services-a"],
      _dark: tokens.colors.dark["hero-gradient-nodes-and-services-a"],
    },
    "hero-gradient-nodes-and-services-b": {
      default: tokens.colors.light["hero-gradient-nodes-and-services-b"],
      _dark: tokens.colors.dark["hero-gradient-nodes-and-services-b"],
    },
    "hero-gradient-security-a": {
      default: tokens.colors.light["hero-gradient-security-a"],
      _dark: tokens.colors.dark["hero-gradient-security-a"],
    },
    "hero-gradient-security-b": {
      default: tokens.colors.light["hero-gradient-security-b"],
      _dark: tokens.colors.dark["hero-gradient-security-b"],
    },
    "hero-subtitle-fg": {
      default: tokens.colors.light["hero-subtitle-fg"],
      _dark: tokens.colors.dark["hero-subtitle-fg"],
    },
    "btn-outline-hero-bg": {
      default: tokens.colors.light["btn-outline-hero-bg"],
      _dark: tokens.colors.dark["btn-outline-hero-bg"],
    },
    "btn-outline-hero-fg": {
      default: tokens.colors.light["btn-outline-hero-fg"],
      _dark: tokens.colors.dark["btn-outline-hero-fg"],
    },
    "btn-outline-hero-border": {
      default: tokens.colors.light["btn-outline-hero-border"],
      _dark: tokens.colors.dark["btn-outline-hero-border"],
    },
    "btn-outline-hero-hover-bg": {
      default: tokens.colors.light["btn-outline-hero-hover-bg"],
      _dark: tokens.colors.dark["btn-outline-hero-hover-bg"],
    },
    "btn-outline-hero-hover-fg": {
      default: tokens.colors.light["btn-outline-hero-hover-fg"],
      _dark: tokens.colors.dark["btn-outline-hero-hover-fg"],
    },
    "btn-outline-hero-hover-border": {
      default: tokens.colors.light["btn-outline-hero-hover-border"],
      _dark: tokens.colors.dark["btn-outline-hero-hover-border"],
    },
    "btn-outline-hero-active-bg": {
      default: tokens.colors.light["btn-outline-hero-active-bg"],
      _dark: tokens.colors.dark["btn-outline-hero-active-bg"],
    },
    "btn-outline-hero-active-fg": {
      default: tokens.colors.light["btn-outline-hero-active-fg"],
      _dark: tokens.colors.dark["btn-outline-hero-active-fg"],
    },
    "btn-outline-hero-active-border": {
      default: tokens.colors.light["btn-outline-hero-active-border"],
      _dark: tokens.colors.dark["btn-outline-hero-active-border"],
    },
    "btn-primary-hero-bg": {
      default: tokens.colors.light["btn-primary-hero-bg"],
      _dark: tokens.colors.dark["btn-primary-hero-bg"],
    },
    "btn-primary-hero-hover-bg": {
      default: tokens.colors.light["btn-primary-hero-hover-bg"],
      _dark: tokens.colors.dark["btn-primary-hero-hover-bg"],
    },
    "btn-primary-hero-active-bg": {
      default: tokens.colors.light["btn-primary-hero-active-bg"],
      _dark: tokens.colors.dark["btn-primary-hero-active-bg"],
    },
    "btn-primary-hero-fg": {
      default: tokens.colors.light["btn-primary-hero-fg"],
      _dark: tokens.colors.dark["btn-primary-hero-fg"],
    },
    "btn-primary-hero-hover-fg": {
      default: tokens.colors.light["btn-primary-hero-hover-fg"],
      _dark: tokens.colors.dark["btn-primary-hero-hover-fg"],
    },
    "btn-primary-hero-active-fg": {
      default: tokens.colors.light["btn-primary-hero-active-fg"],
      _dark: tokens.colors.dark["btn-primary-hero-active-fg"],
    },
    "btn-primary-hero-border": {
      default: tokens.colors.light["btn-primary-hero-border"],
      _dark: tokens.colors.dark["btn-primary-hero-border"],
    },
    "btn-primary-hero-hover-border": {
      default: tokens.colors.light["btn-primary-hero-hover-border"],
      _dark: tokens.colors.dark["btn-primary-hero-hover-border"],
    },
    "btn-primary-hero-active-border": {
      default: tokens.colors.light["btn-primary-hero-active-border"],
      _dark: tokens.colors.dark["btn-primary-hero-active-border"],
    },
    "gradient-orange-a": {
      default: tokens.colors.light["gradient-orange-a"],
      _dark: tokens.colors.dark["gradient-orange-a"],
    },
    "gradient-blue-a": {
      default: tokens.colors.light["gradient-blue-a"],
      _dark: tokens.colors.dark["gradient-blue-a"],
    },
    "gradient-purple-a": {
      default: tokens.colors.light["gradient-purple-a"],
      _dark: tokens.colors.dark["gradient-purple-a"],
    },
    "gradient-cyan-a": {
      default: tokens.colors.light["gradient-cyan-a"],
      _dark: tokens.colors.dark["gradient-cyan-a"],
    },
    "gradient-peach-a": {
      default: tokens.colors.light["gradient-peach-a"],
      _dark: tokens.colors.dark["gradient-peach-a"],
    },
    "gradient-pink-a": {
      default: tokens.colors.light["gradient-pink-a"],
      _dark: tokens.colors.dark["gradient-pink-a"],
    },
    "gradient-blue-default-a": {
      default: tokens.colors.light["gradient-blue-default-a"],
      _dark: tokens.colors.dark["gradient-blue-default-a"],
    },
    "gradient-orange-b": {
      default: tokens.colors.light["gradient-orange-b"],
      _dark: tokens.colors.dark["gradient-orange-b"],
    },
    "gradient-blue-b": {
      default: tokens.colors.light["gradient-blue-b"],
      _dark: tokens.colors.dark["gradient-blue-b"],
    },
    "gradient-purple-b": {
      default: tokens.colors.light["gradient-purple-b"],
      _dark: tokens.colors.dark["gradient-purple-b"],
    },
    "gradient-cyan-b": {
      default: tokens.colors.light["gradient-cyan-b"],
      _dark: tokens.colors.dark["gradient-cyan-b"],
    },
    "gradient-peach-b": {
      default: tokens.colors.light["gradient-peach-b"],
      _dark: tokens.colors.dark["gradient-peach-b"],
    },
    "gradient-pink-b": {
      default: tokens.colors.light["gradient-pink-b"],
      _dark: tokens.colors.dark["gradient-pink-b"],
    },
    "gradient-blue-default-b": {
      default: tokens.colors.light["gradient-blue-default-b"],
      _dark: tokens.colors.dark["gradient-blue-default-b"],
    },
    "roadmap-card-border-color": {
      default: tokens.colors.light["roadmap-card-border-color"],
      _dark: tokens.colors.dark["roadmap-card-border-color"],
    },
    "roadmap-card-tag-border-color": {
      default: tokens.colors.light["roadmap-card-tag-border-color"],
      _dark: tokens.colors.dark["roadmap-card-tag-border-color"],
    },
    "roadmap-card-tag-bg": {
      default: tokens.colors.light["roadmap-card-tag-bg"],
      _dark: tokens.colors.dark["roadmap-card-tag-bg"],
    },
    "roadmap-card-bg-color": {
      default: tokens.colors.light["roadmap-card-bg-color"],
      _dark: tokens.colors.dark["roadmap-card-bg-color"],
    },
    "summit-popup-date-heading-color": {
      default: tokens.colors.light["summit-popup-date-heading-color"],
      _dark: tokens.colors.dark["summit-popup-date-heading-color"],
    },
    "councils-title-fg": {
      default: tokens.colors.light["councils-title-fg"],
      _dark: tokens.colors.dark["councils-title-fg"],
    },
  },
};
