name: "Pull Request Labeler"
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          sync-labels: true
